### ISSUE TITLE
Add more power options listed here

### ISSUE THREAD

**Issue by upintheairsheep** [yume-chan/ya-webadb#376] opened 2022-02-04 05:01 UTC
Long press power button - adb shell input keyevent --longpress 26
Lock Screen - adb shell input keyevent 223
Wake up device - adb shell input keyevent 224
Dim screen - adb shell input keyevent 276

**Comment by yume-chan** [comment] 2022-02-04 06:47
Duplicate of #363

**Closed by yume-chan** 2022-02-04 06:47 UTC
Labels: enhancement
