### ISSUE TITLE
App list

### ISSUE THREAD

**Issue by glitch128** [yume-chan/ya-webadb#456] opened 2022-10-20 15:18 UTC
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A list of installed apps with the options to uninstall or disable them would be nice. This would merge with the "Install APK" page and change the title to "Installed apps".

**Describe alternatives you've considered**
N/A

**Comment by yume-chan** [comment] 2022-10-20 15:20
Duplicate of #373

**Closed by yume-chan** 2022-10-20 15:20 UTC
Labels: type:enhancement
