### ISSUE TITLE
fastboot protocol should be easy to implement

### ISSUE THREAD

**Issue by Zibri** [yume-chan/ya-webadb#452] opened 2022-09-26 13:49 UTC
adding fastboot protocol would be nice..
I made some tests and webusb supports both fastboot both qualcomm qdload and diag...

**Comment by yume-chan** [comment] 2022-09-26 14:00
Duplicate of #343

I don't have BL unlocked devices so I can't test and implement that, but I will accept community contributions.

**Closed by yume-chan** 2022-09-26 14:00 UTC
Labels: type:enhancement

**Comment by Zibri** [comment] 2022-09-26 14:11
> Duplicate of #343
> 
> I don't have BL unlocked devices so I can't test and implement that, but I will accept community contributions.

https://kdrag0n.github.io/fastboot.js/demo/

https://kdrag0n.github.io/fastboot.js

no need to be unlocked to use fastboot...
